parameters:
#    alumnos.example.class: ITM\AlumnosBundle\Example

services:
#    alumnos.example:
#        class: %alumnos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
